### ISSUE TITLE
request.URL.Host could have :443, and it errors out when t.Host is not same. 

### ISSUE THREAD

**Issue by zqingqing1** [Azure/go-armbalancer#2]
When I was doing my testing, the request which contains :443 in the url won't work with the default host "management.azure.com"

Get "https://management.azure.com:443/subscriptions/854c9ddb-fe9e-4aea-8d58-99ed88282881/resourceGroups/MC_qizheebld68817167_large-aks-qizhe_eastus/providers/Microsoft.Compute/virtualMachines?": host "management.azure.com:443" is not supported by the configured ARM balancer

**Comment by jveski** [comment]
Fixed in #3
